Catkin-ProjectName: ecto_opencv
Version: 0.3.7
Description: Ecto bindings for common opencv functionality.
Author: Ethan Rublee <erublee@willowgarage.com>, Troy Straszheim <straszheim@willowgarage.com>
Maintainer:  Vincent Rabaud <vrabaud@willowgarage.com>
Homepage:  http://ecto.willowgarage.com

Depends: catkin, boost, ecto, opencv2

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake
